### ISSUE TITLE
'Index was outside the bounds of the Array' error opening possibly invalid MIDI file

### ISSUE THREAD

**Issue by jonnosan** [jeffbourdier/MIDIopsy#15]
I am trying to open the MIDI file which has a d/l link here
http://www.midi-karaoke.info/21038bb5.html
(direct link to the download is) http://www.midi-karaoke.info/21038bb5.mid

If I open this file in the vanBasco Karaoke Player, I get a warning that the file is damaged and can only be party loaded, but then it finishes loading and plays fine. So there is obviously enough of a valid MIDI file there to be playable.

But when I load it into MIDIopsy, I get an error 'Index was outside the bounds of the Array' and no file is loaded.

It would be nice if it was possible to still show whatever parts of a damaged/malformed file could be interpreted.

**Comment by jeffbourdier** [comment]
Thanks for reporting this.

It appears that the file is indeed damaged/invalid.  The header says that there are 17 tracks, but only 15 are present, and although the 15th track reports a length of 3376 bytes, there are not that many bytes left in the file.  It's as if the last several bytes of the file were truncated (in other words, unexpected end-of-file encountered).

MIDIopsy assumes that the file is complete and attempts to read more bytes than are really there.  (Thus, the exception is thrown.)  I agree it would be better to detect this condition and load as much of the file as possible, but report the error(s) that were encountered while loading.

This would also be a good use case for logging (available via **Settings**, but not currently implemented).  This too will be remedied.

FYI, Windows Media Player will not play the file, so neither will MIDIopsy.  One option might be to load a "repaired" version of the file and play that instead.  (This would be a separate issue.)

**Comment by jeffbourdier** [comment]
Resolved with commit 8c108c830a2bc5f0c02ba2c3f02d84dc4e563ea0.
