### ISSUE TITLE
Settings.Designer.cs file missing from repo

### ISSUE THREAD

**Issue by hclatwr** [jeffbourdier/MIDIopsy#37]
I could not compile the project, VS Studio is complaining about a missing file Settings.Designer.cs
![image](https://user-images.githubusercontent.com/42594229/152596301-54b61a85-cb2c-4981-8e90-28954ef1bd3b.png)

**Comment by jeffbourdier** [comment]
I believe what probably happened here was that the files `Settings.settings` and `Settings.Designer.cs` were autogenerated without me being fully aware of it, and I neglected to include them in the repo.  They can be regenerated from the Settings tab of Project Properties.  I can add them in a future commit.

**Comment by jeffbourdier** [comment]
Resolved with commit 2e1c70acf14916a45710d7a4f5410fd7030c82d8.
