### ISSUE TITLE
MIDI files generated from MIDI-Lector (MIDI Recorder) appear to not be working

### ISSUE THREAD

**Issue by promidi** [jeffbourdier/MIDIopsy#46]
MIDI Files generated by MIDI-Lector (https://orgautomatech.fr/produit/midilector-2/) give out of bounds error:

![image](https://github.com/jeffbourdier/MIDIopsy/assets/49705510/a0a7c3e2-1763-4370-8047-4d49bcf088a9)

Error can be reproduced with this midi file (Dropbox link)

https://www.dropbox.com/scl/fi/l3d5ujbjvm9bdxsq7k4nd/MM004.MID?rlkey=ejs7fcda2wbmmegy8e1z9u7s0&dl=0

**Comment by jeffbourdier** [comment]
Thanks for reporting this.

The example provided has 6 extra bytes at the end of the file that shouldn't really be there, but they're easy enough to ignore.  MIDIopsy now checks for this when loading a file.

Resolved with commit 8d45d0a7a9f9ac50883e2c2f2c1356edbeea8241.
